FROM python:3.11-slim

RUN useradd -m -u 10000 -s /bin/false sandbox && \
    mkdir -p /home/sandbox/bot && \
    chown -R sandbox:sandbox /home/sandbox && \
    chmod 755 /home/sandbox

RUN rm -f /usr/bin/gcc /usr/bin/g++ /usr/bin/make /usr/bin/curl /usr/bin/wget /bin/nc /bin/netcat

RUN pip install --no-cache-dir pyTelegramBotAPI requests

WORKDIR /home/sandbox/bot
USER sandbox

ENTRYPOINT ["timeout", "30"]
CMD ["python", "-c", "import sys; exec(sys.stdin.read())"]
